package com.choxsu.common.entity;


import com.choxsu.common.entity.base.BaseAccountOpen;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccountOpen extends BaseAccountOpen<AccountOpen> {

    /**
     * 授权类型qq
     */
    public static final String OPEN_TYPE_QQ = "qq";
    /**
     * 授权类型weibo
     */
    public static final String OPEN_TYPE_WEIBO = "weibo";
	
}
