package com.choxsu.common.entity;


import com.choxsu.common.entity.base.BaseBlogReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BlogReply extends BaseBlogReply<BlogReply> {
	
}
