package com.choxsu.common.entity;


import com.choxsu.common.entity.base.BaseCodeConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CodeConfig extends BaseCodeConfig<CodeConfig> {
	
}
