package com.choxsu.common.entity;


import com.choxsu.common.entity.base.BaseIpRepository;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IpRepository extends BaseIpRepository<IpRepository> {
	
}
