package com.choxsu.common.entity;


import com.choxsu.common.entity.base.BaseNewsFeed;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsFeed extends BaseNewsFeed<NewsFeed> {

    public static final int REF_TYPE_SHARE = 3;                       // 分享动态
    public static final int REF_TYPE_SHARE_REPLY = 4;            // 分享回复动态


    public boolean isRefTypeShare() {
        return getRefType() == REF_TYPE_SHARE;
    }

    public boolean isRefTypeShareReply() {
        return getRefType() == REF_TYPE_SHARE_REPLY;
    }

}
