package com.choxsu.common.entity;


import com.choxsu.common.entity.base.BaseRemind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Remind extends BaseRemind<Remind> {
    // 提醒类型
    public static final int TYPE_REFER_ME = 0;      // 非数据库字段，仅用于在业务层判断所操作的类型
    public static final int TYPE_MESSAGE = 1;       // 非数据库字段，仅用于在业务层判断所操作的类型
    public static final int TYPE_FANS = 2;          // 非数据库字段，仅用于在业务层判断所操作的类型
}
