package com.choxsu.common.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlogReply<M extends BaseBlogReply<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(Integer id) {
		set("id", id);
	}

	/**
	 * ID
	 */
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 账户ID
	 */
	public void setAccountId(Integer accountId) {
		set("accountId", accountId);
	}

	/**
	 * 账户ID
	 */
	public Integer getAccountId() {
		return getInt("accountId");
	}

	/**
	 * 文章ID
	 */
	public void setBlogId(Integer blogId) {
		set("blogId", blogId);
	}

	/**
	 * 文章ID
	 */
	public Integer getBlogId() {
		return getInt("blogId");
	}

	/**
	 * 评论内容
	 */
	public void setContent(String content) {
		set("content", content);
	}

	/**
	 * 评论内容
	 */
	public String getContent() {
		return getStr("content");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setReport(Integer report) {
		set("report", report);
	}

	public Integer getReport() {
		return getInt("report");
	}

}
