package com.choxsu.common.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVisitor<M extends BaseVisitor<M>> extends Model<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(Integer id) {
		set("id", id);
	}

	/**
	 * 主键id
	 */
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 请求的IP地址
	 */
	public void setIp(String ip) {
		set("ip", ip);
	}

	/**
	 * 请求的IP地址
	 */
	public String getIp() {
		return getStr("ip");
	}

	/**
	 * ip所在地区
	 */
	public void setAddress(String address) {
		set("address", address);
	}

	/**
	 * ip所在地区
	 */
	public String getAddress() {
		return getStr("address");
	}

	/**
	 * 查询结果json
	 */
	public void setAddressJson(String addressJson) {
		set("addressJson", addressJson);
	}

	/**
	 * 查询结果json
	 */
	public String getAddressJson() {
		return getStr("addressJson");
	}

	/**
	 * 请求的页面路径
	 */
	public void setUrl(String url) {
		set("url", url);
	}

	/**
	 * 请求的页面路径
	 */
	public String getUrl() {
		return getStr("url");
	}

	/**
	 * 请求方法
	 */
	public void setMethod(String method) {
		set("method", method);
	}

	/**
	 * 请求方法
	 */
	public String getMethod() {
		return getStr("method");
	}

	/**
	 * 客户端
	 */
	public void setClient(String client) {
		set("client", client);
	}

	/**
	 * 客户端
	 */
	public String getClient() {
		return getStr("client");
	}

	/**
	 * 请求时间
	 */
	public void setRequestTime(java.util.Date requestTime) {
		set("requestTime", requestTime);
	}
	
	/**
	 * 请求时间
	 */
	public java.util.Date getRequestTime() {
		return get("requestTime");
	}

}
