package com.choxsu.common.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIpRepository<M extends BaseIpRepository<M>> extends Model<M> implements IBean {

	/**
	 *  
	 */
	public void setId(Long id) {
		set("id", id);
	}

	/**
	 *
	 */
	public Long getId() {
		return getLong("id");
	}

	/**
	 * IP
	 */
	public void setIp(String ip) {
		set("ip", ip);
	}

	/**
	 * IP
	 */
	public String getIp() {
		return getStr("ip");
	}

	/**
	 * 国家
	 */
	public void setCountry(String country) {
		set("country", country);
	}

	/**
	 * 国家
	 */
	public String getCountry() {
		return getStr("country");
	}

	/**
	 * 区域
	 */
	public void setArea(String area) {
		set("area", area);
	}

	/**
	 * 区域
	 */
	public String getArea() {
		return getStr("area");
	}

	/**
	 * 区域2
	 */
	public void setRegion(String region) {
		set("region", region);
	}

	/**
	 * 区域2
	 */
	public String getRegion() {
		return getStr("region");
	}

	/**
	 * 城市
	 */
	public void setCity(String city) {
		set("city", city);
	}

	/**
	 * 城市
	 */
	public String getCity() {
		return getStr("city");
	}

	/**
	 * 县
	 */
	public void setCounty(String county) {
		set("county", county);
	}

	/**
	 * 县
	 */
	public String getCounty() {
		return getStr("county");
	}

	/**
	 * 运营商
	 */
	public void setIsp(String isp) {
		set("isp", isp);
	}

	/**
	 * 运营商
	 */
	public String getIsp() {
		return getStr("isp");
	}

	/**
	 * 国家代码
	 */
	public void setCountryId(String countryId) {
		set("country_id", countryId);
	}

	/**
	 * 国家代码
	 */
	public String getCountryId() {
		return getStr("country_id");
	}

	public void setAreaId(String areaId) {
		set("area_id", areaId);
	}

	public String getAreaId() {
		return getStr("area_id");
	}

	public void setRegionId(String regionId) {
		set("region_id", regionId);
	}

	public String getRegionId() {
		return getStr("region_id");
	}

	public void setCityId(String cityId) {
		set("city_id", cityId);
	}

	public String getCityId() {
		return getStr("city_id");
	}

	public void setCountyId(String countyId) {
		set("county_id", countyId);
	}

	public String getCountyId() {
		return getStr("county_id");
	}

	public void setIspId(String ispId) {
		set("isp_id", ispId);
	}

	public String getIspId() {
		return getStr("isp_id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
