package com.choxsu.common.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCodeConfig<M extends BaseCodeConfig<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(Long id) {
		set("id", id);
	}

	/**
	 * ID
	 */
	public Long getId() {
		return getLong("id");
	}

	/**
	 * 作者
	 */
	public void setAuthor(String author) {
		set("author", author);
	}

	/**
	 * 作者
	 */
	public String getAuthor() {
		return getStr("author");
	}

	/**
	 * 基础包名
	 */
	public void setBasePackage(String basePackage) {
		set("base_package", basePackage);
	}

	/**
	 * 基础包名
	 */
	public String getBasePackage() {
		return getStr("base_package");
	}

	/**
	 * 实体包名
	 */
	public void setEntityPackage(String entityPackage) {
		set("entity_package", entityPackage);
	}

	/**
	 * 实体包名
	 */
	public String getEntityPackage() {
		return getStr("entity_package");
	}

	/**
	 * service包名
	 */
	public void setServicePackage(String servicePackage) {
		set("service_package", servicePackage);
	}

	/**
	 * service包名
	 */
	public String getServicePackage() {
		return getStr("service_package");
	}

	/**
	 * 实体基础包
	 */
	public void setEntityBasePackage(String entityBasePackage) {
		set("entity_base_package", entityBasePackage);
	}

	/**
	 * 实体基础包
	 */
	public String getEntityBasePackage() {
		return getStr("entity_base_package");
	}

	/**
	 * 是否去除前缀
	 */
	public void setIsClearPrefix(Boolean isClearPrefix) {
		set("is_clear_prefix", isClearPrefix);
	}

	/**
	 * 是否去除前缀
	 */
	public Boolean getIsClearPrefix() {
		return get("is_clear_prefix");
	}

	/**
	 * 前缀
	 */
	public void setPrefix(String prefix) {
		set("prefix", prefix);
	}

	/**
	 * 前缀
	 */
	public String getPrefix() {
		return getStr("prefix");
	}

	/**
	 * BaseModel 是否生成链式 setter 方法
	 */
	public void setIsGenerateChainSetter(Boolean isGenerateChainSetter) {
		set("is_generate_chain_setter", isGenerateChainSetter);
	}

	/**
	 * BaseModel 是否生成链式 setter 方法
	 */
	public Boolean getIsGenerateChainSetter() {
		return get("is_generate_chain_setter");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
