package com.choxsu.common.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(Integer id) {
		set("id", id);
	}

	/**
	 * 主键id
	 */
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 博客主id
	 */
	public void setAccountId(Integer accountId) {
		set("accountId", accountId);
	}

	/**
	 * 博客主id
	 */
	public Integer getAccountId() {
		return getInt("accountId");
	}

	/**
	 * 标题
	 */
	public void setTitle(String title) {
		set("title", title);
	}

	/**
	 * 标题
	 */
	public String getTitle() {
		return getStr("title");
	}

	/**
	 * 内容
	 */
	public void setContent(String content) {
		set("content", content);
	}

	/**
	 * 内容
	 */
	public String getContent() {
		return getStr("content");
	}

	/**
	 * 待解析内容
	 */
	public void setMarkedContent(String markedContent) {
		set("markedContent", markedContent);
	}

	/**
	 * 待解析内容
	 */
	public String getMarkedContent() {
		return getStr("markedContent");
	}

	/**
	 * 创建时间
	 */
	public void setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateAt() {
		return get("createAt");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateAt(java.util.Date updateAt) {
		set("updateAt", updateAt);
	}

	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateAt() {
		return get("updateAt");
	}

	/**
	 * 点击次数
	 */
	public void setClickCount(Integer clickCount) {
		set("clickCount", clickCount);
	}

	/**
	 * 点击次数
	 */
	public Integer getClickCount() {
		return getInt("clickCount");
	}

	/**
	 * 喜欢次数
	 */
	public void setLikeCount(Integer likeCount) {
		set("likeCount", likeCount);
	}

	/**
	 * 喜欢次数
	 */
	public Integer getLikeCount() {
		return getInt("likeCount");
	}

	/**
	 * 收藏次数
	 */
	public void setFavoriteCount(Integer favoriteCount) {
		set("favoriteCount", favoriteCount);
	}

	/**
	 * 收藏次数
	 */
	public Integer getFavoriteCount() {
		return getInt("favoriteCount");
	}

	/**
	 * 类型 note（笔记）favorite(收藏）code(代码）about(关于）
	 */
	public void setCategory(String category) {
		set("category", category);
	}

	/**
	 * 类型 note（笔记）favorite(收藏）code(代码）about(关于）
	 */
	public String getCategory() {
		return getStr("category");
	}

	/**
	 * 是否删除 0否1是
	 */
	public void setIsDelete(Integer isDelete) {
		set("isDelete", isDelete);
	}

	/**
	 * 是否删除 0否1是
	 */
	public Integer getIsDelete() {
		return getInt("isDelete");
	}

	/**
	 * tag_id
	 */
	public void setTagId(Integer tagId) {
		set("tag_id", tagId);
	}

	/**
	 * tag_id
	 */
	public Integer getTagId() {
		return getInt("tag_id");
	}

	/**
	 * 代码分类id，如果category为code时候，这个值才会生效
	 */
	public void setCategoryId(Integer categoryId) {
		set("category_id", categoryId);
	}

	/**
	 * 代码分类id，如果category为code时候，这个值才会生效
	 */
	public Integer getCategoryId() {
		return getInt("category_id");
	}

	/**
	 * 允许评论
	 */
	public void setAllowComments(Boolean allowComments) {
		set("allowComments", allowComments);
	}

	/**
	 * 允许评论
	 */
	public Boolean getAllowComments() {
		return getBoolean("allowComments");
	}

}
